# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ae0304606c3230c28ea5818bf750cca00ee8c1b5119e02e3a28a16bedb36d4f9e57d15d31a9efd4284948e8f87fccbe00c4209e8d9219e3baa1a0fd237b7f26

test:
  secret_key_base: bdea2e13e992d0d7c409ef28ec322b3aee2e611cdbcb7111bcd70aaf788d360bb162ae84c547605a6d602b7675761e17512fbb29ee21196d4f2a9eedd596f114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
